language: node_js
node_js: "lts/*"
jobs:
  include:
    - stage: test
      script: "npm run test:lint"
    - stage: test
      script: "npm run test:security"
    - stage: test
      script: "npm run test:mocha"
    - stage: test
      branches:
        only: master
      script: "npm run test:mocha"
      node_js:
        - "10"
    - stage: release
      on:
          branch: master
      deploy:
        - provider: script
          skip_cleanup: true
          script:
            - npx semantic-release
        - provider: heroku
          skip_cleanup: true
          api_key:
            secure: $HEROKU_API_KEY
          app: telegram-explorer
notifications:
  email:
    recipients: dipustovit@gmail.com
    on_success: change
    on_failure: always